/*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Component renders a 3D barrier model using react-three-fiber
 */

import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

const MODEL_URL =
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/barrier/model.gltf";

type GLTFResult = GLTF & {
  nodes: {
    barrierMedium: THREE.Mesh<
      THREE.BufferGeometry,
      THREE.Material | THREE.Material[]
    >;
  };
  materials: {
    ["Metal.010"]: THREE.MeshStandardMaterial;
  };
};

export default function Barrier(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    MODEL_URL,
    true,
  ) as unknown as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.barrierMedium.geometry}
        material={materials["Metal.010"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
