/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import * as THREE from 'three'
        import React, { useRef } from 'react'
        import { useGLTF, 
        
         } from '@react-three/drei'
        import { GLTF } from "three/examples/jsm/loaders/GLTFLoader"
        
type GLTFResult = GLTF & {
    nodes: {
      barrierMedium: THREE.Mesh
      
    }
    materials: {
      ['Metal.010']: THREE.MeshStandardMaterial
    }
  }

        export default function Model(props: JSX.IntrinsicElements['group']) {
          const group = useRef<THREE.Group>()
          const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/barrier/model.gltf') as GLTFResult
          return (
            <group ref={group} {...props} dispose={null}>
        <mesh geometry={nodes.barrierMedium.geometry} material={materials['Metal.010']} rotation={[Math.PI / 2, 0, 0,]} />

            </group>
          )
        }

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/barrier/model.gltf')