/*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Component renders a 3D house model using react-three-fiber
 */

import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

const MODEL_URL =
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/house-4/model.gltf";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_house_type04: THREE.Mesh;
    Mesh_house_type04_1: THREE.Mesh;
    Mesh_house_type04_2: THREE.Mesh;
    Mesh_house_type04_3: THREE.Mesh;
    Mesh_house_type04_4: THREE.Mesh;
  };
  materials: {
    border: THREE.MeshStandardMaterial;
    door: THREE.MeshStandardMaterial;
    wndow: THREE.MeshStandardMaterial;
    roof: THREE.MeshStandardMaterial;
    main: THREE.MeshStandardMaterial;
  };
};

export default function House2(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    MODEL_URL,
    true,
  ) as unknown as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_house_type04.geometry}
        material={materials.border}
      />
      <mesh
        geometry={nodes.Mesh_house_type04_1.geometry}
        material={materials.door}
      />
      <mesh
        geometry={nodes.Mesh_house_type04_2.geometry}
        material={materials.wndow}
      />
      <mesh
        geometry={nodes.Mesh_house_type04_3.geometry}
        material={materials.roof}
      />
      <mesh
        geometry={nodes.Mesh_house_type04_4.geometry}
        material={materials.main}
      />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
