/*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Component renders a 3D SUV model using react-three-fiber
 */

import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

const MODEL_URL =
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/suv/model.gltf";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_wheel_frontLeft006: THREE.Mesh;
    Mesh_wheel_frontLeft006_1: THREE.Mesh;
    Mesh_wheel_frontLeft007: THREE.Mesh;
    Mesh_wheel_frontLeft007_1: THREE.Mesh;
    Mesh_wheel_frontLeft008: THREE.Mesh;
    Mesh_wheel_frontLeft008_1: THREE.Mesh;
    Mesh_body001: THREE.Mesh;
    Mesh_body001_1: THREE.Mesh;
    Mesh_body001_2: THREE.Mesh;
    Mesh_body001_3: THREE.Mesh;
    Mesh_body001_4: THREE.Mesh;
    Mesh_body001_5: THREE.Mesh;
    Mesh_wheel_frontLeft005: THREE.Mesh;
    Mesh_wheel_frontLeft005_1: THREE.Mesh;
    Mesh_wheel_frontLeft004: THREE.Mesh;
    Mesh_wheel_frontLeft004_1: THREE.Mesh;
  };
  materials: {
    carTire: THREE.MeshStandardMaterial;
    ["_defaultMat.021"]: THREE.MeshStandardMaterial;
    ["plastic.001"]: THREE.MeshStandardMaterial;
    paintGreen: THREE.MeshStandardMaterial;
    ["window.021"]: THREE.MeshStandardMaterial;
    lightBack: THREE.MeshStandardMaterial;
    lightFront: THREE.MeshStandardMaterial;
  };
};

export default function Suv(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    MODEL_URL,
    true,
  ) as unknown as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={-1}>
        <mesh
          geometry={nodes.Mesh_wheel_frontLeft006.geometry}
          material={materials.carTire}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontLeft006_1.geometry}
          material={materials["_defaultMat.021"]}
        />
      </group>
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft007.geometry}
        material={materials.carTire}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft007_1.geometry}
        material={materials["_defaultMat.021"]}
      />
      <group scale={-1}>
        <mesh
          geometry={nodes.Mesh_wheel_frontLeft008.geometry}
          material={materials.carTire}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontLeft008_1.geometry}
          material={materials["_defaultMat.021"]}
        />
      </group>
      <mesh
        geometry={nodes.Mesh_body001.geometry}
        material={materials["plastic.001"]}
      />
      <mesh
        geometry={nodes.Mesh_body001_1.geometry}
        material={materials.paintGreen}
      />
      <mesh
        geometry={nodes.Mesh_body001_2.geometry}
        material={materials["plastic.001"]}
      />
      <mesh
        geometry={nodes.Mesh_body001_3.geometry}
        material={materials["window.021"]}
      />
      <mesh
        geometry={nodes.Mesh_body001_4.geometry}
        material={materials.lightBack}
      />
      <mesh
        geometry={nodes.Mesh_body001_5.geometry}
        material={materials.lightFront}
      />
      <group scale={-1}>
        <mesh
          geometry={nodes.Mesh_wheel_frontLeft005.geometry}
          material={materials.carTire}
        />
        <mesh
          geometry={nodes.Mesh_wheel_frontLeft005_1.geometry}
          material={materials["_defaultMat.021"]}
        />
      </group>
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft004.geometry}
        material={materials.carTire}
      />
      <mesh
        geometry={nodes.Mesh_wheel_frontLeft004_1.geometry}
        material={materials["_defaultMat.021"]}
      />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
