/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import * as THREE from 'three'
        import React, { useRef } from 'react'
        import { useGLTF, 
        
         } from '@react-three/drei'
        import { GLTF } from "three/examples/jsm/loaders/GLTFLoader"
        
type GLTFResult = GLTF & {
    nodes: {
      Mesh_wheel_frontLeft006: THREE.Mesh,Mesh_wheel_frontLeft006_1: THREE.Mesh,Mesh_wheel_frontLeft007: THREE.Mesh,Mesh_wheel_frontLeft007_1: THREE.Mesh,Mesh_wheel_frontLeft008: THREE.Mesh,Mesh_wheel_frontLeft008_1: THREE.Mesh,Mesh_body001: THREE.Mesh,Mesh_body001_1: THREE.Mesh,Mesh_body001_2: THREE.Mesh,Mesh_body001_3: THREE.Mesh,Mesh_body001_4: THREE.Mesh,Mesh_body001_5: THREE.Mesh,Mesh_wheel_frontLeft005: THREE.Mesh,Mesh_wheel_frontLeft005_1: THREE.Mesh,Mesh_wheel_frontLeft004: THREE.Mesh,Mesh_wheel_frontLeft004_1: THREE.Mesh
      
    }
    materials: {
      carTire: THREE.MeshStandardMaterial,['_defaultMat.021']: THREE.MeshStandardMaterial,['plastic.001']: THREE.MeshStandardMaterial,paintGreen: THREE.MeshStandardMaterial,['window.021']: THREE.MeshStandardMaterial,lightBack: THREE.MeshStandardMaterial,lightFront: THREE.MeshStandardMaterial
    }
  }

        export default function Model(props: JSX.IntrinsicElements['group']) {
          const group = useRef<THREE.Group>()
          const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/suv/model.gltf') as GLTFResult
          return (
            <group ref={group} {...props} dispose={null}>
        <group scale={-1} >
<mesh geometry={nodes.Mesh_wheel_frontLeft006.geometry} material={nodes.Mesh_wheel_frontLeft006.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft006_1.geometry} material={nodes.Mesh_wheel_frontLeft006_1.material} />
</group>
<mesh geometry={nodes.Mesh_wheel_frontLeft007.geometry} material={nodes.Mesh_wheel_frontLeft007.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft007_1.geometry} material={nodes.Mesh_wheel_frontLeft007_1.material} />
<group scale={-1} >
<mesh geometry={nodes.Mesh_wheel_frontLeft008.geometry} material={nodes.Mesh_wheel_frontLeft008.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft008_1.geometry} material={nodes.Mesh_wheel_frontLeft008_1.material} />
</group>
<mesh geometry={nodes.Mesh_body001.geometry} material={materials['plastic.001']} />
<mesh geometry={nodes.Mesh_body001_1.geometry} material={materials.paintGreen} />
<mesh geometry={nodes.Mesh_body001_2.geometry} material={nodes.Mesh_body001_2.material} />
<mesh geometry={nodes.Mesh_body001_3.geometry} material={materials['window.021']} />
<mesh geometry={nodes.Mesh_body001_4.geometry} material={materials.lightBack} />
<mesh geometry={nodes.Mesh_body001_5.geometry} material={materials.lightFront} />
<group scale={-1} >
<mesh geometry={nodes.Mesh_wheel_frontLeft005.geometry} material={nodes.Mesh_wheel_frontLeft005.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft005_1.geometry} material={nodes.Mesh_wheel_frontLeft005_1.material} />
</group>
<mesh geometry={nodes.Mesh_wheel_frontLeft004.geometry} material={nodes.Mesh_wheel_frontLeft004.material} />
<mesh geometry={nodes.Mesh_wheel_frontLeft004_1.geometry} material={nodes.Mesh_wheel_frontLeft004_1.material} />

            </group>
          )
        }

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/suv/model.gltf')