/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import * as THREE from 'three'
        import React, { useRef } from 'react'
        import { useGLTF, 
        
         } from '@react-three/drei'
        import { GLTF } from "three/examples/jsm/loaders/GLTFLoader"
        
type GLTFResult = GLTF & {
    nodes: {
      Mesh_tree_large: THREE.Mesh,Mesh_tree_large_1: THREE.Mesh
      
    }
    materials: {
      ['roof.002']: THREE.MeshStandardMaterial,['wood.001']: THREE.MeshStandardMaterial
    }
  }

        export default function Model(props: JSX.IntrinsicElements['group']) {
          const group = useRef<THREE.Group>()
          const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-big/model.gltf') as GLTFResult
          return (
            <group ref={group} {...props} dispose={null}>
        <mesh geometry={nodes.Mesh_tree_large.geometry} material={materials['roof.002']} />
<mesh geometry={nodes.Mesh_tree_large_1.geometry} material={materials['wood.001']} />

            </group>
          )
        }

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-big/model.gltf')