/*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Component renders a 3D lime tree model using react-three-fiber
 */

import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

const MODEL_URL =
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-lime/model.gltf";

type GLTFResult = GLTF & {
  nodes: {
    "tree-lime": THREE.Mesh;
  };
  materials: {
    color_main: THREE.MeshStandardMaterial;
  };
};

export default function TreeLime(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    MODEL_URL,
    true,
  ) as unknown as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes["tree-lime"].geometry}
        material={materials.color_main}
      />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
