/*
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Component renders a 3D flat truck model using react-three-fiber
 */

import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

const MODEL_URL =
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/truck-flat/model.gltf";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_wheel_frontLeft001: THREE.Mesh;
    Mesh_wheel_frontLeft001_1: THREE.Mesh;
    Mesh_wheel_frontLeft001_2: THREE.Mesh;
    Mesh_body001: THREE.Mesh;
    Mesh_body001_1: THREE.Mesh;
    Mesh_body001_2: THREE.Mesh;
    Mesh_body001_3: THREE.Mesh;
    Mesh_body001_4: THREE.Mesh;
    Mesh_body001_5: THREE.Mesh;
  };
  materials: {
    ["carTire.001"]: THREE.MeshStandardMaterial;
    ["_defaultMat.001"]: THREE.MeshStandardMaterial;
    ["plastic.001"]: THREE.MeshStandardMaterial;
    plastic: THREE.MeshStandardMaterial;
    window: THREE.MeshStandardMaterial;
    lightBack: THREE.MeshStandardMaterial;
    paintWhite: THREE.MeshStandardMaterial;
    lightFront: THREE.MeshPhysicalMaterial;
    _defaultMat: THREE.MeshStandardMaterial;
  };
};

export default function TruckFlat(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    MODEL_URL,
    true,
  ) as unknown as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]}>
        <group position={[-0.35, 0.3, 0.64]} scale={[-1, 1, 1]}>
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001.geometry}
            material={materials["carTire.001"]}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001_1.geometry}
            material={materials["_defaultMat.001"]}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001_2.geometry}
            material={materials["plastic.001"]}
          />
        </group>
        <group
          position={[0.35, 0.3, 0.64]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        >
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001.geometry}
            material={materials["carTire.001"]}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001_1.geometry}
            material={materials["_defaultMat.001"]}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001_2.geometry}
            material={materials["plastic.001"]}
          />
        </group>
        <group position={[-0.35, 0.3, -0.78]} scale={[-1, 1, 1]}>
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001.geometry}
            material={materials["carTire.001"]}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001_1.geometry}
            material={materials["_defaultMat.001"]}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001_2.geometry}
            material={materials["plastic.001"]}
          />
        </group>
        <group
          position={[0.35, 0.3, -0.78]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-1, 1, 1]}
        >
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001.geometry}
            material={materials["carTire.001"]}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001_1.geometry}
            material={materials["_defaultMat.001"]}
          />
          <mesh
            geometry={nodes.Mesh_wheel_frontLeft001_2.geometry}
            material={materials["plastic.001"]}
          />
        </group>
        <group position={[0, 0.2, -0.12]}>
          <mesh
            geometry={nodes.Mesh_body001.geometry}
            material={materials.plastic}
          />
          <mesh
            geometry={nodes.Mesh_body001_1.geometry}
            material={materials.window}
          />
          <mesh
            geometry={nodes.Mesh_body001_2.geometry}
            material={materials.lightBack}
          />
          <mesh
            geometry={nodes.Mesh_body001_3.geometry}
            material={materials.paintWhite}
          />
          <mesh
            geometry={nodes.Mesh_body001_4.geometry}
            material={materials.lightFront}
          />
          <mesh
            geometry={nodes.Mesh_body001_5.geometry}
            material={materials._defaultMat}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(MODEL_URL);
