/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import * as THREE from 'three'
        import React, { useRef } from 'react'
        import { useGLTF, 
        
         } from '@react-three/drei'
        import { GLTF } from "three/examples/jsm/loaders/GLTFLoader"
        
type GLTFResult = GLTF & {
    nodes: {
      Mesh_wheel_frontRight001: THREE.Mesh,Mesh_wheel_frontRight001_1: THREE.Mesh,Mesh_wheel_frontRight002: THREE.Mesh,Mesh_wheel_frontRight002_1: THREE.Mesh,Mesh_wheel_frontRight003: THREE.Mesh,Mesh_wheel_frontRight003_1: THREE.Mesh,Mesh_wheel_frontRight: THREE.Mesh,Mesh_wheel_frontRight_1: THREE.Mesh,Mesh_body003: THREE.Mesh,Mesh_body003_1: THREE.Mesh,Mesh_body003_2: THREE.Mesh,Mesh_body003_3: THREE.Mesh,Mesh_body003_4: THREE.Mesh,Mesh_body003_5: THREE.Mesh
      
    }
    materials: {
      ['carTire.003']: THREE.MeshStandardMaterial,['plastic.003']: THREE.MeshStandardMaterial,plastic: THREE.MeshStandardMaterial,paintYellow: THREE.MeshStandardMaterial,lightFront: THREE.MeshPhysicalMaterial,_defaultMat: THREE.MeshStandardMaterial,window: THREE.MeshStandardMaterial,lightBack: THREE.MeshStandardMaterial
    }
  }

        export default function Model(props: JSX.IntrinsicElements['group']) {
          const group = useRef<THREE.Group>()
          const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/taxi/model.gltf') as GLTFResult
          return (
            <group ref={group} {...props} dispose={null}>
        <group scale={1.3} >
<mesh geometry={nodes.Mesh_wheel_frontRight001.geometry} material={nodes.Mesh_wheel_frontRight001.material} />
<mesh geometry={nodes.Mesh_wheel_frontRight001_1.geometry} material={nodes.Mesh_wheel_frontRight001_1.material} />
<mesh geometry={nodes.Mesh_wheel_frontRight002.geometry} material={nodes.Mesh_wheel_frontRight002.material} />
<mesh geometry={nodes.Mesh_wheel_frontRight002_1.geometry} material={nodes.Mesh_wheel_frontRight002_1.material} />
<mesh geometry={nodes.Mesh_wheel_frontRight003.geometry} material={nodes.Mesh_wheel_frontRight003.material} />
<mesh geometry={nodes.Mesh_wheel_frontRight003_1.geometry} material={nodes.Mesh_wheel_frontRight003_1.material} />
<mesh geometry={nodes.Mesh_wheel_frontRight.geometry} material={nodes.Mesh_wheel_frontRight.material} />
<mesh geometry={nodes.Mesh_wheel_frontRight_1.geometry} material={nodes.Mesh_wheel_frontRight_1.material} />
<mesh geometry={nodes.Mesh_body003.geometry} material={materials.plastic} />
<mesh geometry={nodes.Mesh_body003_1.geometry} material={materials.paintYellow} />
<mesh geometry={nodes.Mesh_body003_2.geometry} material={materials.lightFront} />
<mesh geometry={nodes.Mesh_body003_3.geometry} material={materials._defaultMat} />
<mesh geometry={nodes.Mesh_body003_4.geometry} material={materials.window} />
<mesh geometry={nodes.Mesh_body003_5.geometry} material={materials.lightBack} />
</group>

            </group>
          )
        }

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/taxi/model.gltf')